#!/usr/bin/env python3
"""Generate Project-Summary.md — daily index of everything the project touches.
Output goes to stdout; caller writes to the wiki project folder."""
import datetime, json, pathlib, subprocess

WS = pathlib.Path("/Users/jakeclaw/.openclaw/workspace")
PS = WS / "project-state"
WIKI = pathlib.Path("/Users/jakeclaw/wiki")
DATA = pathlib.Path("/Users/jakeclaw/workers/data/phgdh")
today = datetime.date.today().isoformat()

def audit(path):
    p = pathlib.Path(path)
    if not p.exists():
        return "_not found_"
    st = p.stat()
    mt = datetime.datetime.fromtimestamp(st.st_mtime).strftime("%Y-%m-%d %H:%M")
    size = st.st_size
    human = f"{size:,} B" if size < 1024 else (f"{size/1024:.1f} KB" if size < 1024**2 else f"{size/1024**2:.1f} MB")
    return f"{human}, {mt}"

def list_reports(level, limit=7):
    d = PS / "reports" / f"L{level}"
    if not d.exists(): return []
    return sorted(d.glob("*.md"), reverse=True)[:limit]

def get_iter_state():
    try: return json.loads((PS / "iteration_state.json").read_text())
    except Exception: return {"task":"?","iteration":0,"stage":"?"}

iter_s = get_iter_state()

# Parse CURRENT_GOAL for Task + Aim
cg_text = (PS / "CURRENT_GOAL.md").read_text() if (PS / "CURRENT_GOAL.md").exists() else ""
import re
aim_m = re.search(r"\*\*Aim:\*\*\s*(Aim \d[^\n]*)", cg_text)
task_m = re.search(r"\*\*Task:\*\*\s*(Task \d+\.\d+)", cg_text)
goal_m = re.search(r"## Goal\s*\n(.+?)(?=\n##)", cg_text, re.DOTALL)

aim = aim_m.group(1) if aim_m else "unknown"
task = task_m.group(1) if task_m else "unknown"
goal_text = (goal_m.group(1).strip().split('\n')[0] if goal_m else "unknown")

# Count artifacts
data_files = sorted(DATA.glob("*.jsonl")) if DATA.exists() else []
phgdh_pages = list(WIKI.rglob("*phgdh*.md")) if WIKI.exists() else []
figures_dir = WS / "figures"
figures = sorted(figures_dir.glob("*")) if figures_dir.exists() else []

# Completed / pending counts
cd_text = (PS / "COMPLETED.md").read_text() if (PS / "COMPLETED.md").exists() else ""
done_count = len(re.findall(r"^## G-\d+", cd_text, re.M))
bl_text = (PS / "BACKLOG.md").read_text() if (PS / "BACKLOG.md").exists() else ""
pending_count = len(re.findall(r"^\|\s*Task \d+\.\d+\s*\|", bl_text, re.M))

out = []
out.append("---")
out.append(f"title: \"PHGDH Project — Daily Summary\"")
out.append(f"date: {today}")
out.append(f"category: index")
out.append(f"tier: live")
out.append(f"source: auto-generated by daily_wiki_publish.sh")
out.append("---")
out.append("")
out.append(f"# PHGDH Project — Daily Summary ({today})")
out.append("")
out.append("> Auto-generated each evening at 17:05. Links point to the public wiki where available; GitHub where only code; W0 paths for local-only artifacts.")
out.append("")
out.append(f"## Current iteration")
out.append(f"- **{aim}**")
out.append(f"- Active: **{task}**  ·  iteration **{iter_s.get('iteration','?')}**  ·  stage **{iter_s.get('stage','?')}**")
out.append(f"- Goal: *{goal_text}*")
out.append(f"- Completed so far: {done_count}  |  Pending backlog: {pending_count}")
out.append("")
out.append("## Live documents (this wiki)")
out.append("| Document | Audit |")
out.append("|----------|-------|")
for name, src in [
    ("Master Blueprint", "[[Master-Blueprint]]"),
    ("LIVE: Project Plan", "[[LIVE-PROJECT_PLAN]]"),
    ("LIVE: Design Notes", "[[LIVE-DESIGN_NOTES]]"),
    ("LIVE: PHGDH Brief", "[[LIVE-PHGDH_BRIEF]]"),
    ("LIVE: Current Goal", "[[LIVE-CURRENT_GOAL]]"),
    ("LIVE: Backlog", "[[LIVE-BACKLOG]]"),
    ("LIVE: Agent Rules", "[[LIVE-CLAUDE]]"),
    ("LIVE: Resolution Log", "[[LIVE-RESOLUTION_LOG]]"),
]:
    ws_file = WS / (name.replace("LIVE: ", "").replace(" ", "_").upper() + ".md") if "LIVE:" in name else None
    out.append(f"| {src} | — |")
out.append("")
out.append("## Recent reports")
out.append("### L1 (one-sentence pings, last 3)")
for f in list_reports(1, 3):
    out.append(f"- `{f.name}` — {audit(f)}")
out.append("")
out.append("### L2 (daily digests, last 7)")
for f in list_reports(2, 7):
    name = f.stem
    out.append(f"- [[daily-summaries/{name}|{name}]] — {audit(f)}")
out.append("")
out.append("### L3+ (PLEASER iterations)")
for lvl in [3,4,5,6]:
    reports = list_reports(lvl, 3)
    if reports:
        out.append(f"**L{lvl}:**")
        for f in reports:
            out.append(f"- `{f.name}` — {audit(f)}")
out.append("")
out.append("## Scavenged data (local — W0)")
out.append(f"- Total daily JSONL files: {len(data_files)}")
if data_files:
    latest = data_files[-1]
    out.append(f"- Latest: `{latest.name}` — {audit(latest)}")
out.append("")
out.append("## Figures (local — W0)")
if figures:
    for f in figures[:10]:
        out.append(f"- `{f.name}` — {audit(f)}")
else:
    out.append("- _(none yet — pending Task 2.1 and later)_")
out.append("")
out.append("## Wiki pages (PHGDH topics)")
out.append(f"- Total PHGDH-named .md pages across wiki: {len(phgdh_pages)}")
out.append("- See: [[phgdh-research/]] · [[PHGDH-topics/]] · [[phgdh-scavenger]]")
out.append("")
out.append("## GitHub")
out.append("- [phgdh-scavenger repo](https://github.com/jakechen1/phgdh-scavenger)")
out.append("- [echo-research-framework repo](https://github.com/jakechen1/echo-research-framework)")
out.append("- [sdd-wiki (this site source)](https://github.com/aimed-lab/sdd-wiki)")
out.append("")
out.append("## Infrastructure health")
try:
    listing = subprocess.check_output("/usr/bin/sudo -n /bin/launchctl list 2>/dev/null | /usr/bin/grep -cE 'ai\\.(jakeclaw|hermes)|com\\.(jakeclaw|openclaw)'", shell=True, text=True).strip()
    out.append(f"- LaunchDaemons registered: {listing}")
except Exception:
    out.append("- LaunchDaemons: unknown")
out.append("")
out.append("---")
out.append(f"*Generated {datetime.datetime.now().isoformat(timespec='seconds')} by `daily_wiki_publish.sh` on jakeclaw@mac-w0.*")
print("\n".join(out))
